### ISSUE TITLE
Better container positioning

### ISSUE THREAD

**Issue by p3lim** [p3lim-wow/LibContainer#2]
Allow in-game customizing with docking/anchoring.
Maybe draw some inspiration from how WeakAuras does it (the visual part atleast).

**Comment by p3lim** [comment]
First pass:
https://github.com/p3lim-wow/Backpack/commit/6267e4ec38e4f76a95b28baf10068aa31570d25e
https://github.com/p3lim-wow/Backpack/commit/25478b9289a6bac7d7d8d4b4ef54816991469548

Now has proper positioning for the parent containers (inventory ones), and lets the rest of the containers grow properly and not go off-screen.

**Comment by xtoq** [comment]
I think this fits here, but if I need to open a separate ticket, just say the word.

# Backpack strata issue with Xloot's loot monitor

Steps to reproduce
-----

1. Have Xloot installed with the Loot Monitor enabled and placed somewhere the Backpack windows will appear on top.
2. Be in a group and have things show up in the loot monitor, or try the "test" option in the options (YMMV with the latter).
3. Open Backpack.

Expected outcome
-----

- Backpack should appear above the Loot Monitor.


Actual outcome
-----

- Some Backpack windows appear above the Loot Monitor strata while some appear below. See attached screenshot. It's a bit hard to see, but Equipment Sets is below the Loot Monitor, while New Items is above.

![image](https://cloud.githubusercontent.com/assets/120364/19826442/467a0262-9d50-11e6-8971-cb1bc5a6de7f.png)

**Comment by p3lim** [comment]
Might want to leave this up to layouts, they can override the positioning system quite easily now.

**Comment by p3lim** [comment]
A container order feature is planned, any interactivity beyond that is up to the layout to implement.
