### ISSUE TITLE
Container.columns only affecting base container

### ISSUE THREAD

**Issue by Solor** [p3lim-wow/LibContainer#34]
is there a way to set how many containers in 1 row

![untitled](https://cloud.githubusercontent.com/assets/156806/21664951/ba67ed42-d324-11e6-892c-c5b7c308350a.jpg)

```Container.columns = 10``` only apply to bottom container

![untitled1](https://cloud.githubusercontent.com/assets/156806/21665032/29db8544-d325-11e6-9f3a-94b846465a8c.jpg)

**Comment by p3lim** [comment]
For the first one, see your previous issue (#33).
For the second one, I'll take a look into that, thanks for reporting.

**Comment by solor** [comment]
```Container.slotSizeY = 40
		Container.slotSizeX = 40
		Container.spacingX = 1
		Container.spacingY = 1
		Container.columns = 10```

all these are only apply to bottom container
