### ISSUE TITLE
Increase frame strata

### ISSUE THREAD

**Issue by bullsei** [p3lim-wow/LibContainer#39]
- What version are you using?
70300.14-Beta
- Can the issue be reproduced, and if so, how?

It would be nice of the frame strata of the backpack could be increased. I just wanted to change a artifact relict but its impossible because i can't reach the item in my backback since the backpack is behind the artifact window.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Backpack/issues/16

**Comment by bullsei** [comment]
Saw that issue. I thought this issue is only related to Xloot. Thats why i created a new one.

**Comment by p3lim** [comment]
I could add a config option for it, I can understand the need for it.

**Comment by bullsei** [comment]
Thanks, i really like this addon, but thats really a issue for me which makes me going back to adibags. This problem makes it also impossible for me to sell something on the auction house. Looking forward to that setting :)

**Comment by p3lim** [comment]
Layouts can easily implement this.
